name: github_user_list
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-96.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  share: ^2.0.4
  flutter_staggered_grid_view: ^0.7.0 
  flutter_bloc: ^8.1.4
  dio: ^5.4.0
  get_it: ^7.6.7
  bloc: ^8.1.3
  equatable: ^2.0.5
  connectivity: ^3.0.6
  provider: ^6.1.1
  easy_localization: ^3.0.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/image/
  - assets/translations/